version: 2
registries:
  github-package-registry:
    type: maven-repository
    url: https://maven.pkg.github.com/svIndicium/*
    username: ${{ secrets.GH_PKG_USERNAME }}
    password: ${{ secrets.DEPENDABOT_TOKEN }}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - github-package-registry
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
